kind: pipeline
type: docker
name: Golang文件系统扩展


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: plugins/git
    pull: always

  - name: 编译
    image: pangum/drone
    pull: always
    settings:
      output: gfx
