kind: pipeline
type: docker
name: Golang外部调用扩展


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: always

  - name: 编译
    image: pangum/drone
    pull: always
    when:
      branch:
        - master
        - develop
    volumes:
      - name: go
        path: /go
    settings:
      test: false
      compress: false


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
