kind: pipeline
type: docker
name: Golang文件系统扩展


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: always

  - name: 编译
    image: pangum/drone
    pull: always

  - name: 文档
    image: dronestock/node
    pull: always
    settings:
      folder: doc

  - name: 部署
    image: dronestock/cos
    pull: always
    depends_on:
      - 文档
    settings:
      folder: doc/dist
      secret_id:
        from_secret: secret_id_cos
      secret_key:
        from_secret: secret_key_cos
      base_url: https://gex-1253228583.cos.ap-chengdu.myqcloud.com
